[book]
title = "Time"
authors = ["Jacob Pratt"]
language = "en"
multilingual = false
src = "src"
create-missing = false

[rust]
edition = "2021"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/time-rs/book/edit/main/{path}"
git-repository-url = "https://github.com/time-rs/book"

[output.html.playground]
editable = true
runnable = false
line-numbers = true
